-- MySQL Script generated by MySQL Workbench
-- Fri Dec 28 20:10:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`BlockManager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BlockManager` ;
/*
CREATE TABLE IF NOT EXISTS `mydb`.`BlockManager` (
  `BlockManagerNo` INT NOT NULL,
  `ManagedNo` INT NOT NULL,
  PRIMARY KEY (`BlockManagerNo`),
  INDEX `BlockNo_idx` (`ManagedNo` ASC) VISIBLE,
  CONSTRAINT `ManagedNo`
    FOREIGN KEY (`ManagedNo`)
    REFERENCES `mydb`.`Blocks` (`BlocksNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BlockManagerNo`
    FOREIGN KEY (`BlockManagerNo`)
    REFERENCES `mydb`.`Users` (`UserNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
*/

-- -----------------------------------------------------
-- Table `mydb`.`Blocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`posts_blocks` ;

CREATE TABLE IF NOT EXISTS `mydb`.`posts_blocks` (
  `block_id` INT NOT NULL AUTO_INCREMENT,
  `block_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`block_id`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `mydb`.`videos_blocks` ;

CREATE TABLE IF NOT EXISTS `mydb`.`videos_blocks` (
  `block_id` INT NOT NULL AUTO_INCREMENT,
  `block_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`block_id`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `mydb`.`files_blocks` ;

CREATE TABLE IF NOT EXISTS `mydb`.`files_blocks` (
  `block_id` INT NOT NULL AUTO_INCREMENT,
  `block_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`block_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DatabaseManager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DatabaseManager` ;
/*
CREATE TABLE IF NOT EXISTS `mydb`.`DatabaseManager` (
  `DatabaseManagerNo` INT NOT NULL,
  PRIMARY KEY (`DatabaseManagerNo`),
  CONSTRAINT `DatabaseManagerNo`
    FOREIGN KEY (`DatabaseManagerNo`)
    REFERENCES `mydb`.`Users` (`UserNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
*/

-- -----------------------------------------------------
-- Table `mydb`.`Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`posts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`posts` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `block_id` INT NOT NULL,
  `post_user_id` INT NOT NULL,
  `post_user_name` VARCHAR(20) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `content` VARCHAR(200) NOT NULL,
  -- `clicks` INT NOT NULL,
  `reply_num` INT NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `block_id_idx` (`block_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`post_user_id` ASC) VISIBLE,
  CONSTRAINT `post_block_id`
    FOREIGN KEY (`block_id`)
    REFERENCES `mydb`.`posts_blocks` (`block_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_user_id`
    FOREIGN KEY (`post_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `mydb`.`videos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`videos` (
  `video_id` INT NOT NULL AUTO_INCREMENT,
  `block_id` INT NOT NULL,
  `video_user_id` INT NOT NULL,
  `video_user_name` VARCHAR(20) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `path` VARCHAR(100) NOT NULL,
  -- `content` VARCHAR(200) NOT NULL,
  -- `clicks` INT NOT NULL,
  `visit_num` INT NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`video_id`),
  INDEX `block_id_idx` (`block_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`video_user_id` ASC) VISIBLE,
  CONSTRAINT `video_block_id`
    FOREIGN KEY (`block_id`)
    REFERENCES `mydb`.`videos_blocks` (`block_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `video_user_id`
    FOREIGN KEY (`video_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `mydb`.`files` ;

CREATE TABLE IF NOT EXISTS `mydb`.`files` (
  `file_id` INT NOT NULL AUTO_INCREMENT,
  `block_id` INT NOT NULL,
  `file_user_id` INT NOT NULL,
  `file_user_name` VARCHAR(20) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `path` VARCHAR(100) NOT NULL,
  -- `content` VARCHAR(200) NOT NULL,
  -- `clicks` INT NOT NULL,
  `reply_num` INT NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`file_id`),
  INDEX `block_id_idx` (`block_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`file_user_id` ASC) VISIBLE,
  CONSTRAINT `file_block_id`
    FOREIGN KEY (`block_id`)
    REFERENCES `mydb`.`files_blocks` (`block_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `file_user_id`
    FOREIGN KEY (`file_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Replies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`replies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`replies` (
  `reply_id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `floor` INT NOT NULL,
  `reply_user_id` INT NOT NULL,
  `reply_user_name` VARCHAR(20) NOT NULL,
  `reply_content` VARCHAR(200) NOT NULL,
  `reply_time` DATETIME NOT NULL,
  -- `praise_num` INT NOT NULL,
  PRIMARY KEY (`reply_id`),
  INDEX `post_id_idx` (`post_id` ASC) VISIBLE,
  INDEX `reply_user_id_idx` (`reply_user_id` ASC) VISIBLE,
  CONSTRAINT `post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`posts` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reply_user_id`
    FOREIGN KEY (`reply_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(20) NOT NULL,
  `gender` VARCHAR(10) NOT NULL default "male",
  `level` INT NOT NULL default 0,
  `birthday` DATE NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `reg_date` DATE NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WaterUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`WaterUser` ;
/*
CREATE TABLE IF NOT EXISTS `mydb`.`WaterUser` (
  `WaterUserNo` INT NOT NULL,
  UNIQUE INDEX `WaterUserNo_UNIQUE` (`WaterUserNo` ASC) VISIBLE,
  PRIMARY KEY (`WaterUserNo`),
  CONSTRAINT `WaterUserNo`
    FOREIGN KEY (`WaterUserNo`)
    REFERENCES `mydb`.`Users` (`UserNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
*/

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
